---
title: "enesmith"
author: "Elisabeth Nesmith"
date: "3/20/2021"
output: html_document
---

```{r packages, include=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(here)
library(plotly)
```

```{r load-data, message=FALSE}
#load data
meteorological_data <- read_xlsx(here("data", "Sensor Data", "Meteorological Data.xlsx"))
sensor_data <- read_xlsx(here("data", "Sensor Data", "Sensor Data.xlsx"))
lekagul_sensor_data <- read_csv(here("data", "Traffic Data", "Lekagul Sensor Data.csv"))
```

```{r data-cleaning}
#using Marium's code to clean
meteorological_data <- meteorological_data %>%
  clean_names() %>%
  select(-x4)
sensor_data <- sensor_data %>% clean_names()
lekagul_sensor_data <- lekagul_sensor_data %>%
  clean_names() %>%
  mutate(car_type = as.factor(car_type))
```

```{r}
#trying to plot sensors and factories on map

#creating dataframe of factories and sensors and their coordinates (info from sensor data descriptions doc)

name <- c("Roadrunner", "Kasios", "Radiance", "Indigo", "Sensor 1", "Sensor 2", "Sensor 3", "Sensor 4", "Sensor 5", "Sensor 6", "Sensor 7", "Sensor 8", "Sensor 9")

x_location <- c(89, 90, 109, 120, 62, 66, 76, 88, 103, 102, 89, 74, 119)

y_location <- c(27, 21, 26, 22, 21, 35, 41, 45, 43, 22, 3, 7, 42)

type <- c("factory", "factory","factory","factory", "sensor", "sensor", "sensor", "sensor", "sensor", "sensor", "sensor", "sensor", "sensor")

locations <- data.frame(name, x_location, y_location, type)
```

```{r}
#plotting locations of sensors and factories from location data frame on map, using code from my rmd in DC2

fig1 <- locations %>% 
  plot_ly(x = ~x_location,
    y = ~y_location,
    type = 'scatter',
    mode = 'markers',
    color = ~type,
    text = ~name) %>%
    layout(
      images = list(source = "https://raw.githubusercontent.com/mariumtapal/sds325-dc3/master/data/Traffic%20Data/Lekagul%20Roadways%20labeled%20v2.jpg",
           xref = "x",
           yref = "y",
           x = 0,
           y = 200,
           sizex = 200,
           sizey = 200,
           sizing = "stretch",
           opacity = 1,
           layer = "below")) 

fig1 <- fig1 %>% layout(
    xaxis = list(range = c(0, 200)),
    yaxis = list(range = c(0, 200)))
fig1
```

